controleaereo/src/main/java/br/com/controleaereo/managedbeans/VooManagedBean.java
package br.com.controleaereo.managedbeans;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.dozer.Mapper;

import br.com.controleaereo.bean.Assento;
import br.com.controleaereo.bean.Trecho;
import br.com.controleaereo.bean.Usuario;
import br.com.controleaereo.bean.Voo;
import br.com.controleaereo.bo.AssentoBO;
import br.com.controleaereo.bo.VooBO;

@ManagedBean(name = "voo")
@SessionScoped
public class VooManagedBean {

	private HttpSession getSession() {
		HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
				.getExternalContext().getSession(false);
		return session;
	}

	private Usuario getUsuario() {
		Usuario u = (Usuario) getSession().getAttribute("userSession");
		return u;
	}

	private Logger log = LogManager.getLogger(VooManagedBean.class.getName());

	private Trecho trecho = new Trecho();

	private Voo voo;

	private List<Trecho> trechos;

	private List<Assento> assentos;

	private Integer assentosEconomica;

	private Integer assentosExecutiva;

	private String selectedAssentos;

	@SuppressWarnings("unused")
	private Double valorTotal;

	private Double multa;

	public Double getMulta() {
		if (multa == null) {
			return new Double(0);
		}
		return multa;
	}

	public void setMulta(Double multa) {
		this.multa = multa;
	}

	public Double getValorTotal() {
		int qtdAssentos = getAssentoSelecionados().size();
		double total = 0;
		for (Trecho trecho : getVoo().getTrechos()) {
			total += trecho.getPreco();
		}
		return (total * qtdAssentos) + getMulta();
	}

	public void setValorTotal(Double valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Voo getVoo() {
		return voo;
	}

	public void setVoo(Voo voo) {
		this.voo = voo;
	}

	public List<Assento> getAssentos() {
		return assentos;
	}

	public void setAssentos(List<Assento> assentos) {
		this.assentos = assentos;
	}

	public String getSelectedAssentos() {
		return selectedAssentos;
	}

	public void setSelectedAssentos(String selectedAssentos) {
		this.selectedAssentos = selectedAssentos;
	}

	public Integer getAssentosEconomica() {
		return assentosEconomica;
	}

	public void setAssentosEconomica(Integer assentosEconomica) {
		this.assentosEconomica = assentosEconomica;
	}

	public Integer getAssentosExecutiva() {
		return assentosExecutiva;
	}

	public void setAssentosExecutiva(Integer assentosExecutiva) {
		this.assentosExecutiva = assentosExecutiva;
	}

	public Trecho getTrecho() {
		return trecho;
	}

	public void setTrecho(Trecho trecho) {
		this.trecho = trecho;
	}

	public List<Trecho> getTrechos() {
		if (this.trechos == null) {
			this.trechos = new ArrayList<Trecho>();
		}
		return this.trechos;
	}

	public void setTrechos(List<Trecho> trechos) {
		this.trechos = trechos;
	}

	public String cadastrarVoo() {
		if (trechos.size() != 0 && assentosEconomica != 0
				&& assentosExecutiva != 0) {
			Mapper mapper = new DozerBeanMapper();
			Voo voo = mapper.map(this, Voo.class);
			List<Assento> assentos = new ArrayList<Assento>();
			for (int i = 0; i < assentosEconomica; i++) {
				assentos.add(new Assento("economica", voo));
			}
			for (int i = 0; i < assentosExecutiva; i++) {
				assentos.add(new Assento("executiva", voo));
			}
			try {
				VooBO.getInstance().cadastra(voo, assentos);
			} catch (Exception e) {
				log.error(e.getMessage());
			}
		}
		setAssentosEconomica(null);
		setAssentosExecutiva(null);
		setTrecho(new Trecho());
		setTrechos(null);
		return "CadastroVoo.jsf";
	}

	public String addTrecho() {
		if (validateFields()) {
			Set<Trecho> list = new LinkedHashSet<Trecho>(trechos);
			list.add(trecho);
			setTrechos(new ArrayList<Trecho>(list));
		}
		trecho = new Trecho();
		return null;
	}

	public String remTrecho() {
		getTrechos().remove(trecho);
		return null;
	}

	public boolean validateFields() {
		List<String> fields = new ArrayList<String>();
		if ("".equals(trecho.getNomeTrecho1())) {
			fields.add(" Origem");
		}
		if ("".equals(trecho.getNomeTrecho2())) {
			fields.add(" Destino");
		}
		if (trecho.getPreco() == null) {
			trecho.setPreco(null);
			fields.add(" Preço");
		}
		if ("".equals(trecho.getDataHora())) {
			fields.add(" Data Hora");
		}
		if ((!"".equals(trecho.getNomeTrecho1()))
				&& (!"".equals(trecho.getNomeTrecho2()))
				&& trecho.getNomeTrecho1().equals(trecho.getNomeTrecho2())) {
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR,
							"Origem e destinos não devem ser iguais", ""));
			return false;
		}
		if (fields.size() == 0) {
			return true;
		} else {
			StringBuffer msg = new StringBuffer();
			if (fields.size() > 1) {
				msg.append("Preencha os campos");
			} else {
				msg.append("Preencha o campo");
			}
			for (int i = 0; i < fields.size(); i++) {
				if (i != fields.size() - 1 && i != 0) {
					msg.append(", ");
				} else if (i != 0) {
					msg.append(" e ");
				}
				msg.append(fields.get(i));
			}
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, msg
							.toString(), ""));
		}
		return false;
	}

	public List<Voo> getVoos() {
		List<Voo> voos = VooBO.getInstance().recuperaVoos();
		return voos;
	}

	public List<Voo> getVoosReservados() {
		List<Voo> voos = VooBO.getInstance().recuperaVoosReservados(
				getUsuario());
		return voos;
	}

	public Voo getVooById() {
		Voo voo = null;
		Map<String, String> params = FacesContext.getCurrentInstance()
				.getExternalContext().getRequestParameterMap();
		if (params.get("voo") != null) {
			voo = VooBO.getInstance().recuperaVoo(new Long(params.get("voo")));
			setVoo(voo);
		}
		return voo;
	}

	public List<Assento> getAssentoList() {
		List<Assento> assentosList = AssentoBO.getInstance()
				.recuperaAssentosDisponiveis(getUsuario(), getVoo().getId());
		setAssentos(assentosList);
		return assentos;
	}

	public List<Assento> getAssentoSelecionados() {
		if (getVoo() == null) {
			setVoo(getVooById());
		}
		List<Assento> assentosList = AssentoBO.getInstance()
				.recuperaAssentoSelecionados(getUsuario(), getVoo().getId());
		boolean fechado = false;
		if (assentosList != null && assentosList.get(0) != null
				&& assentosList.get(0).getFechado()) {
			getSession().setAttribute("fechado", true);
		}
		return assentosList;
	}

	public String reservar() {
		String[] selecteds = selectedAssentos.split(",");
		AssentoBO.getInstance().reservar(getUsuario(), getAssentos(),
				selecteds, voo.getId());
		return "confirmacao.jsf";
	}

	public String alterar() {
		// acrescenta multa de 50 reais;
		setMulta(50 + getMulta());
		return "alterarAssentos.jsf";
	}

	public String cancelar() {
		setMulta(50D + getMulta());
		try {
			AssentoBO.getInstance().cancelar(getUsuario(), getVoo().getId());
		} catch (Exception e) {
			log.error(e.getMessage());
		}
		return "escolhaVoo.jsf";
	}

	public String finalizar() {
		try {
			AssentoBO.getInstance().finalizar(getUsuario(), getVoo().getId());
		} catch (Exception e) {
			log.error(e.getMessage());
		}
		return "menuUsuario.jsf";
	}

}

controleaereo/src/main/webapp/paginas/alterarAssentos.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jstl/functions"
	>
<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
		
		
		function selecteds(){
			var inputs=document.getElementsByTagName("input");
			var selecteds = new Array();
			cont = inputs.length -1;
			while(cont != 0){
				i = inputs[cont];
				if(i.type=='checkbox'){
					if(i.checked){
						selecteds.push(i.value);
						//i.disabled=true;
					}
				}
				cont--;
			}
			document.getElementById("form1:selecteds").value=selecteds.toString();
		}
	</script>
</h:head>
<h:body onload="selecteds()">
<h:form id="form1">
<p:inputText id="selecteds" name="selecteds" value="#{voo.selectedAssentos}" style="display:block;" />
<div class="quadro" style="width:500px;padding:10px;">
		<div style="float:right;">
			<p:commandLink id="sairBtn" actionListener="#{clientes.sair}">
        		Sair
    		</p:commandLink>
		</div>
		<div style="float:left;">
			<p:commandLink id="menuBtn" action="menuUsuario.jsf">
	        	Menu
	    	</p:commandLink>
		</div>
		<div class="form" style="width:400px;">
			<h3>Escolha os Assentos</h3>
			<p:dataTable id="listaTrechos" var="trecho" value="#{voo.vooById.trechos}"
				rowKey="#{voo}" selectionMode="single" style="width:370px;">
				<p:column headerText="Trechos">
					<h:outputText value="#{trecho.nomeTrecho1} - #{trecho.nomeTrecho2}" />
				</p:column>
				<p:column headerText="Valor">
					R$ <h:outputText value="#{trecho.preco}" />
				</p:column>
			</p:dataTable>
			<br /><br />
			
			<p:dataTable var="assen" value="#{voo.assentoList}">
				<p:column headerText="Assento">
					<input type="checkbox" name="assento#{assen.id}" id="assento#{assen.id}"
						checked="#{assen.selected}" value="#{assen.id}" onClick="selecteds()" />
					<label for="assento#{assen.id}">
						<h:outputText value="assento #{assen.id}" />
					</label>
				</p:column>
				<p:column headerText="Tipo">
					<h:outputText value="#{assen.tipo}"/>
				</p:column>
			</p:dataTable>
 			<p:commandButton value="Confirmar" action="#{voo.reservar}"
           		ajax="false" />
		</div>
	</div>
</h:form>
</h:body>
</html>

controleaereo/src/main/webapp/paginas/confirmacao.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jstl/functions"
	>
<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
		
		
	</script>
</h:head>
<h:body onload="selecteds()">
<h:form id="form1">
<p:inputText id="selecteds" name="selecteds" value="#{voo.selectedAssentos}" style="display:none;" />
<div class="quadro" style="width:530px;padding:10px;">
		<div style="float:right;">
			<p:commandLink id="sairBtn" actionListener="#{clientes.sair}">
	        	Sair
	    	</p:commandLink>
		</div>
		<div style="float:left;">
			<p:commandLink id="menuBtn" action="menuUsuario.jsf">
	        	Menu
	    	</p:commandLink>
		</div>
		<div class="form" style="width:420px;">
			<h3 id="titulo">Confirmação da reserva</h3>
			<p:dataTable id="listaTrechos" var="trecho" value="#{voo.voo.trechos}"
				rowKey="#{voo}" selectionMode="single" style="width:400px;">
				<p:column headerText="Trechos">
					<h:outputText value="#{trecho.nomeTrecho1} - #{trecho.nomeTrecho2}" />
				</p:column>
				<p:column headerText="Valor">
					R$ <h:outputText value="#{trecho.preco}" />
				</p:column>
			</p:dataTable>
			<br /><br />
			<c:set var="fechado" scope="session" value="${false}"/>
			<p:dataTable var="selecionados" value="#{voo.assentoSelecionados}" style="width:400px;">
				<p:column headerText="Assento Escolhidos">
					<h:outputText value="assento #{selecionados.id}" />
				</p:column>
				<p:column headerText="Tipo">
					<h:outputText value="#{selecionados.tipo}"/>
				</p:column>
				<p:column headerText="Tipo">
					<h:outputText value="#{fechado}"/>
				</p:column>
			</p:dataTable>
			<br />
			<b><h:outputText value="Multa: #{voo.multa}" id="multa" /></b>
			<br />			
			<b><h:outputText value="Valor Total: #{voo.valorTotal}" id="precoTotal" /></b>
			<br />
			<br />
 				<p:commandButton value="Finalizar" action="#{voo.finalizar}"
           			ajax="false" rendered="#{!fechado}" />
           			
	 			<p:commandButton value="Alterar" action="#{voo.alterar}"
	           		ajax="false" rendered="#{!fechado}"  />
				<p:commandButton value="Cancelar Reserva" action="#{voo.cancelar}"
	           		ajax="false" rendered="#{!fechado}"  />
		</div>
	</div>
	<script>
		if(<h:outputText value="#{fechado}"/> == true){
			document.getElementById('titulo').textContent='Reserva Finalizada';
		}
	</script>
</h:form>
</h:body>
</html>

controleaereo/src/main/webapp/paginas/escolhaAssentos.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jstl/functions"
	>
<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
		
		
		function selecteds(str){
			var inputs=document.getElementsByTagName("input");
			var selecteds = new Array();
			cont = inputs.length -1;
			while(cont != 0){
				i = inputs[cont];
				if(i.type=='checkbox'){
					if(i.checked){
						selecteds.push(i.value);
						if(str=='onload'){
							i.disabled=true;
						}
					}
				}
				cont--;
			}
			if(selecteds.length != 0){
				document.getElementById("form1:selecteds").value=selecteds.toString();
				if(str=='onload'){
					window.location.href="confirmacao.jsf";
				}
			}else{
				document.getElementById("form1:cancelarBtn").style.display="none";
				document.getElementById("form1:alterarBtn").style.display="none";
			}
		}
	</script>
</h:head>
<h:body onload="selecteds('onload')">
<h:form id="form1">
<p:inputText id="selecteds" name="selecteds" value="#{voo.selectedAssentos}" style="display:none;" />
<div class="quadro" style="width:500px;padding:10px;">
		<div style="float:right;">
			<p:commandLink id="sairBtn" actionListener="#{clientes.sair}">
        		Sair
    		</p:commandLink>
		</div>
		<div style="float:left;">
			<p:commandLink id="menuBtn" action="menuUsuario.jsf">
	        	Menu
	    	</p:commandLink>
		</div>
		<div class="form" style="width:400px;">
			<h3>Escolha os Assentos</h3>
			<p:dataTable id="listaTrechos" var="trecho" value="#{voo.vooById.trechos}"
				rowKey="#{voo}" selectionMode="single" style="width:370px;">
				<p:column headerText="Trechos">
					<h:outputText value="#{trecho.nomeTrecho1} - #{trecho.nomeTrecho2}" />
				</p:column>
				<p:column headerText="Valor">
					R$ <h:outputText value="#{trecho.preco}" />
				</p:column>
			</p:dataTable>
			<br /><br />
			
			<p:dataTable var="assen" value="#{voo.assentoList}">
				<p:column headerText="Assento">
					<input type="checkbox" name="assento#{assen.id}" id="assento#{assen.id}"
						checked="#{assen.selected}" value="#{assen.id}" onClick="selecteds('')" />
					<label for="assento#{assen.id}">
						<h:outputText value="assento #{assen.id}" />
					</label>
				</p:column>
				<p:column headerText="Tipo">
					<h:outputText value="#{assen.tipo}"/>
				</p:column>
			</p:dataTable>
			<br />
 			<p:commandButton value="Reservar" action="#{voo.reservar}"
           		ajax="false" />
           	<p:commandButton value="Cancelar" action="#{voo.cancelar}"
         		ajax="false" id="cancelarBtn" />
           	<p:commandButton value="Alterar" action="#{voo.alterar}"
           		ajax="false" id="alterarBtn" />
		</div>
	</div>
</h:form>
</h:body>
</html>

controleaereo/src/main/webapp/paginas/escolhaVoo.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
	</script>
</h:head>
<h:body>
<h:form>
	<div class="quadro" style="height:400px;width:500px;padding:10px;">
		<div style="float:right;">
			<p:commandLink id="sairBtn" action="#{clientes.sair}">  
	       		Sair  
	    	</p:commandLink>
		</div>
		<div style="float:left;">
			<p:commandLink id="menuBtn" action="menuUsuario.jsf">
	        	Menu
	    	</p:commandLink>
		</div>
		<div class="form">
			<h3>Escolha o Vôo</h3>
			<p:dataTable id="listaTrechos" var="listVoos" value="#{voo.voos}"
				rowKey="#{voo.voos}" selectionMode="single" style="width:350px;">
				<p:column headerText="Voos">
					<h:commandLink action="escolhaAssentos.jsf?voo=listVoos.id" value="#{listVoos.trechos[0].nomeTrecho1} - #{listVoos.trechos[fn:length(listVoos.trechos)-1].nomeTrecho2}">
						<f:param name="voo" value="#{listVoos.id}" />
					</h:commandLink>
				</p:column>
				<p:column headerText="Trechos">
					<h:outputText value="#{fn:length(listVoos.trechos)}" />
				</p:column>
			</p:dataTable>
		</div>
	</div>
</h:form>
</h:body>
</html>

controleaereo/src/main/webapp/paginas/menuUsuario.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
.height{
	height:400px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
	</script>
</h:head>
<h:body>
	<div class="quadro">
		<div style="float:right;padding:10px;">
			<h:form>
				<h:commandLink id="sairBtn" action="#{clientes.sair}">  
		       		<b>Sair</b>
		    	</h:commandLink>
	    	</h:form>
		</div>
		<div class="form height">
			<h3>Olá, <h:outputLabel for="nome" value="#{clientes.nome}" /></h3>
			<a href="escolhaVoo.jsf">Lista de Voos</a>
			<br />
			<br />
			<a href="reservasRealizadasVoos.jsf">Reservas Realizadas</a>
		</div>
	</div>
</h:body>
</html>

controleaereo/src/main/webapp/paginas/reservasRealizadas.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jstl/functions"
	>
<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
		
		
	</script>
</h:head>
<h:body onload="selecteds()">
<h:form id="form1">
<p:inputText id="selecteds" name="selecteds" value="#{voo.selectedAssentos}" style="display:none;" />
<div class="quadro" style="width:530px;padding:10px;">
		<div style="float:right;">
			<p:commandLink id="sairBtn" actionListener="#{clientes.sair}">
	        	Sair
	    	</p:commandLink>
		</div>
		<div style="float:left;">
			<p:commandLink id="menuBtn" action="menuUsuario.jsf">
	        	Menu
	    	</p:commandLink>
		</div>
		<div class="form" style="width:420px;">
			<h3>Reserva Realizadas</h3>
			<p:dataTable id="listaTrechos" var="trecho" value="#{voo.voo.trechos}"
				rowKey="#{voo}" selectionMode="single" style="width:400px;">
				<p:column headerText="Trechos">
					<h:outputText value="#{trecho.nomeTrecho1} - #{trecho.nomeTrecho2}" />
				</p:column>
				<p:column headerText="Valor">
					R$ <h:outputText value="#{trecho.preco}" />
				</p:column>
			</p:dataTable>
			<br /><br />
			
			<p:dataTable var="selecionados" value="#{voo.assentoSelecionados}" style="width:400px;">
				<p:column headerText="Assento Escolhidos">
					<h:outputText value="assento #{selecionados.id}" />
				</p:column>
				<p:column headerText="Tipo">
					<h:outputText value="#{selecionados.tipo}"/>
				</p:column>
			</p:dataTable>
			<br />
			<b><h:outputText value="Multa: #{voo.multa}" id="multa" /></b>
			<br />			
			<b><h:outputText value="Valor Total: #{voo.valorTotal}" id="precoTotal" /></b>
			<br />
			<br />
       		<c:if test="${btns}">
 				<p:commandButton value="Finalizar" action="#{voo.finalizar}"
           			ajax="false" />
	 			<p:commandButton value="Alterar" action="#{voo.alterar}"
	           		ajax="false" />
				<p:commandButton value="Cancelar Reserva" action="#{voo.cancelar}"
	           		ajax="false" />
       		</c:if>
       		<c:if test="${!btns}">
				<script>
					document.getElementById('titulo').textContent='Reserva Finalizada';
				</script>
			</c:if>
		</div>

	</div>
</h:form>
</h:body>
</html>

controleaereo/src/main/webapp/paginas/reservasRealizadasVoos.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>
	<link href="../css/style.css" rel="stylesheet" type="text/css" />
	<style>
.ui-messages-error-summary {
	font-size: 12px;
}

.ui-messages {
	width: 300px;
	position: relative;
	left: -50px;
	top: -10px;
}
</style>
	<link rel="stylesheet" href="../css/uniform.default.css" media="screen" />
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="js/jquery.uniform.js"></script>
	<title>Login</title>
	<script>
		$(function() {
			$("select").uniform();
			$("input").uniform();
		});
	</script>
</h:head>
<h:body>
<h:form>
	<div class="quadro" style="height:400px;width:500px;padding:10px;">
		<div style="float:right;">
			<p:commandLink id="sairBtn" action="#{clientes.sair}">  
	       		Sair  
	    	</p:commandLink>
		</div>
		<div style="float:left;">
			<p:commandLink id="menuBtn" action="menuUsuario.jsf">
	        	Menu
	    	</p:commandLink>
		</div>
		<div class="form">
			<h3>Escolha o Vôo</h3>
			<p:dataTable id="listaTrechos" var="listVoos" value="#{voo.voosReservados}"
				rowKey="#{voo.voos}" selectionMode="single" style="width:350px;">
				<p:column headerText="Voos">
					<h:commandLink action="reservasRealizadas.jsf?voo=listVoos.id" value="#{listVoos.trechos[0].nomeTrecho1} - #{listVoos.trechos[fn:length(listVoos.trechos)-1].nomeTrecho2}">
						<f:param name="voo" value="#{listVoos.id}" />
					</h:commandLink>
				</p:column>
				<p:column headerText="Trechos">
					<h:outputText value="#{fn:length(listVoos.trechos)}" />
				</p:column>
			</p:dataTable>
		</div>
	</div>
</h:form>
</h:body>
</html>